############## clock and reset define##################
create_clock -period 20 [get_ports sys_clk]
set_property IOSTANDARD LVCMOS33 [get_ports {sys_clk}]
set_property PACKAGE_PIN U18 [get_ports {sys_clk}]

set_property IOSTANDARD LVCMOS33 [get_ports {rst_n}]
set_property PACKAGE_PIN N15 [get_ports {rst_n}]
############## HDMI_O###########################
set_property IOSTANDARD TMDS_33 [get_ports TMDS_clk_n]
set_property PACKAGE_PIN N18 [get_ports TMDS_clk_p]
set_property IOSTANDARD TMDS_33 [get_ports TMDS_clk_p]
set_property IOSTANDARD TMDS_33 [get_ports {TMDS_data_n[0]}]
set_property PACKAGE_PIN V20 [get_ports {TMDS_data_p[0]}]
set_property IOSTANDARD TMDS_33 [get_ports {TMDS_data_p[0]}]
set_property IOSTANDARD TMDS_33 [get_ports {TMDS_data_n[1]}]
set_property PACKAGE_PIN T20 [get_ports {TMDS_data_p[1]}]
set_property IOSTANDARD TMDS_33 [get_ports {TMDS_data_p[1]}]
set_property IOSTANDARD TMDS_33 [get_ports {TMDS_data_n[2]}]
set_property PACKAGE_PIN N20 [get_ports {TMDS_data_p[2]}]
set_property IOSTANDARD TMDS_33 [get_ports {TMDS_data_p[2]}]
set_property PACKAGE_PIN V16 [get_ports hdmi_oen]
set_property IOSTANDARD LVCMOS33 [get_ports hdmi_oen]

### Asynchronous clock domain crossings ###
set_false_path -through [get_pins -filter {NAME =~ */SyncAsync*/oSyncStages*/PRE || NAME =~ */SyncAsync*/oSyncStages*/CLR} -hier]
set_false_path -through [get_pins -filter {NAME =~ *SyncAsync*/oSyncStages_reg[0]/D} -hier]
########AN706 ON AX7020 and AX7010  J11##################
set_property PACKAGE_PIN F17 [get_ports {ad7606_os[1]}]
set_property PACKAGE_PIN F16 [get_ports {ad7606_os[0]}]
set_property PACKAGE_PIN F20 [get_ports ad7606_convstab]
set_property PACKAGE_PIN F19 [get_ports {ad7606_os[2]}]
set_property PACKAGE_PIN G20 [get_ports ad7606_rd]
set_property PACKAGE_PIN G19 [get_ports ad7606_reset]
set_property PACKAGE_PIN H18 [get_ports ad7606_busy]
set_property PACKAGE_PIN J18 [get_ports ad7606_cs]
set_property PACKAGE_PIN L19 [get_ports ad7606_first_data]
set_property PACKAGE_PIN K18 [get_ports {ad7606_data[0]}]
set_property PACKAGE_PIN K17 [get_ports {ad7606_data[1]}]
set_property PACKAGE_PIN J19 [get_ports {ad7606_data[2]}]
set_property PACKAGE_PIN K19 [get_ports {ad7606_data[3]}]
set_property PACKAGE_PIN H20 [get_ports {ad7606_data[4]}]
set_property PACKAGE_PIN J20 [get_ports {ad7606_data[5]}]
set_property PACKAGE_PIN L17 [get_ports {ad7606_data[6]}]
set_property PACKAGE_PIN L16 [get_ports {ad7606_data[7]}]
set_property PACKAGE_PIN M18 [get_ports {ad7606_data[8]}]
set_property PACKAGE_PIN M17 [get_ports {ad7606_data[9]}]
set_property PACKAGE_PIN D20 [get_ports {ad7606_data[10]}]
set_property PACKAGE_PIN D19 [get_ports {ad7606_data[11]}]
set_property PACKAGE_PIN E19 [get_ports {ad7606_data[12]}]
set_property PACKAGE_PIN E18 [get_ports {ad7606_data[13]}]
set_property PACKAGE_PIN G18 [get_ports {ad7606_data[14]}]
set_property PACKAGE_PIN G17 [get_ports {ad7606_data[15]}]



set_property IOSTANDARD LVCMOS33 [get_ports ad7606_convstab]
set_property IOSTANDARD LVCMOS33 [get_ports ad7606_reset]
set_property IOSTANDARD LVCMOS33 [get_ports ad7606_rd]
set_property IOSTANDARD LVCMOS33 [get_ports ad7606_cs]
set_property IOSTANDARD LVCMOS33 [get_ports ad7606_busy]
set_property IOSTANDARD LVCMOS33 [get_ports ad7606_first_data]
set_property IOSTANDARD LVCMOS33 [get_ports {ad7606_os[*]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ad7606_data[*]}]