#pragma line 1 "scalar_add/add.cpp" ::: -10
#pragma line 1 "scalar_add/add.cpp" 1 ::: -9
#pragma line 1 "<built-in>" 1 ::: -8
#pragma line 1 "<built-in>" 3 ::: -7
#pragma line 152 "<built-in>" 3 ::: -6
#pragma line 1 "<command line>" 1 ::: -5
#pragma line 1 "C:/Xilinx/Vivado/2017.4/common/technology/autopilot\\etc/autopilot_ssdm_op.h" 1 ::: 3
#pragma line 156 "C:/Xilinx/Vivado/2017.4/common/technology/autopilot\\etc/autopilot_ssdm_op.h" ::: 4
#pragma line 9 "<command line>" 2 ::: 134
#pragma line 1 "<built-in>" 2 ::: 135
#pragma line 1 "scalar_add/add.cpp" 2 ::: 136
