set_property BITSTREAM.GENERAL.COMPRESS TRUE [current_design]
set_property CFGBVS VCCO [current_design]
set_property CONFIG_VOLTAGE 3.3 [current_design]

#J10
set_property PACKAGE_PIN T16      [get_ports {cmos1_i2c_sda_io}]
set_property PACKAGE_PIN V18     [get_ports {cmos1_d[9]}]
set_property PACKAGE_PIN V17     [get_ports {cmos1_d[8]}]
set_property PACKAGE_PIN T15     [get_ports {cmos1_i2c_scl_io}]
set_property PACKAGE_PIN T14     [get_ports {cmos1_d[5]}]
set_property PACKAGE_PIN V13     [get_ports {cmos1_d[3]}]
set_property PACKAGE_PIN U13     [get_ports {cmos1_d[4]}]
set_property PACKAGE_PIN W13     [get_ports {cmos1_d[6]}]
set_property PACKAGE_PIN V12     [get_ports {cmos1_d[0]}]
set_property PACKAGE_PIN U12     [get_ports {cmos1_d[7]}]
set_property PACKAGE_PIN T12     [get_ports {cmos1_d[1]}]
set_property PACKAGE_PIN T10     [get_ports {cmos1_d[2]}]
set_property PACKAGE_PIN T11     [get_ports {cmos1_pclk}]
set_property PACKAGE_PIN A20     [get_ports {cmos1_href}]
set_property PACKAGE_PIN B19     [get_ports {cmos1_vsync}]
set_property PACKAGE_PIN B20     [get_ports {cmos_rstn_tri_o[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports {cmos1_i2c_sda_io}]
set_property IOSTANDARD LVCMOS33 [get_ports {cmos1_d[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cmos1_d[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cmos1_i2c_scl_io}]
set_property IOSTANDARD LVCMOS33 [get_ports {cmos1_d[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cmos1_d[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cmos1_d[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cmos1_d[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cmos1_d[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cmos1_d[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cmos1_d[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cmos1_d[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cmos1_pclk}]
set_property IOSTANDARD LVCMOS33 [get_ports {cmos1_href}]
set_property IOSTANDARD LVCMOS33 [get_ports {cmos1_vsync}]
set_property IOSTANDARD LVCMOS33 [get_ports {cmos_rstn_tri_o[0]}]
set_property PULLUP true [get_ports cmos1_i2c_scl_io]
set_property PULLUP true [get_ports cmos1_i2c_sda_io]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets cmos1_pclk_IBUF]

#set_property IOSTANDARD LVCMOS33 [get_ports {cmos2_vsync}]
#set_property IOSTANDARD LVCMOS33 [get_ports {cmos2_pclk}]
#set_property PACKAGE_PIN W19 [get_ports {cmos2_d[9]}]
#set_property PACKAGE_PIN W18 [get_ports {cmos2_i2c_sda_io}]
#set_property PACKAGE_PIN R14 [get_ports {cmos2_d[6]}]
#set_property PACKAGE_PIN P14 [get_ports {cmos2_i2c_scl_io}]
#set_property PACKAGE_PIN Y17 [get_ports {cmos2_d[7]}]
#set_property PACKAGE_PIN Y16 [get_ports {cmos2_d[2]}]
#set_property PACKAGE_PIN W15 [get_ports {cmos2_href}]
#set_property PACKAGE_PIN V15 [get_ports {cmos2_d[8]}]
#set_property PACKAGE_PIN Y14 [get_ports {cmos2_d[3]}]
#set_property PACKAGE_PIN W14 [get_ports {cmos_rstn_tri_o[1]}]
#set_property PACKAGE_PIN P18 [get_ports {cmos2_d[4]}]
#set_property PACKAGE_PIN N17 [get_ports {cmos2_d[5]}]
#set_property PACKAGE_PIN U15 [get_ports {cmos2_d[1]}]
#set_property PACKAGE_PIN U14 [get_ports {cmos2_d[0]}]
#set_property PACKAGE_PIN P16 [get_ports {cmos2_vsync}]
#set_property PACKAGE_PIN P15 [get_ports {cmos2_pclk}]

#set_property IOSTANDARD LVCMOS33 [get_ports {cmos2_d[9]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {cmos2_i2c_sda_io}]
#set_property IOSTANDARD LVCMOS33 [get_ports {cmos2_d[6]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {cmos2_i2c_scl_io}]
#set_property IOSTANDARD LVCMOS33 [get_ports {cmos2_d[7]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {cmos2_d[2]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {cmos2_href}]
#set_property IOSTANDARD LVCMOS33 [get_ports {cmos2_d[8]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {cmos2_d[3]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {cmos_rstn_tri_o[1]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {cmos2_d[4]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {cmos2_d[5]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {cmos2_d[1]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {cmos2_d[0]}]


#set_property PULLUP true [get_ports cmos2_i2c_scl_io]
#set_property PULLUP true [get_ports cmos2_i2c_sda_io]

#set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets cmos2_pclk_IBUF]

set_property IOSTANDARD TMDS_33 [get_ports TMDS_clk_n]
set_property PACKAGE_PIN N18 [get_ports TMDS_clk_p]
set_property IOSTANDARD TMDS_33 [get_ports TMDS_clk_p]
set_property IOSTANDARD TMDS_33 [get_ports {TMDS_data_n[0]}]
set_property PACKAGE_PIN V20 [get_ports {TMDS_data_p[0]}]
set_property IOSTANDARD TMDS_33 [get_ports {TMDS_data_p[0]}]
set_property IOSTANDARD TMDS_33 [get_ports {TMDS_data_n[1]}]
set_property PACKAGE_PIN T20 [get_ports {TMDS_data_p[1]}]
set_property IOSTANDARD TMDS_33 [get_ports {TMDS_data_p[1]}]
set_property IOSTANDARD TMDS_33 [get_ports {TMDS_data_n[2]}]
set_property PACKAGE_PIN N20 [get_ports {TMDS_data_p[2]}]
set_property IOSTANDARD TMDS_33 [get_ports {TMDS_data_p[2]}]
#set_property PACKAGE_PIN Y19 [get_ports {hdmi_hpd_tri_i[0]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {hdmi_hpd_tri_i[0]}]
set_property PACKAGE_PIN V16 [get_ports hdmi_oen]
set_property IOSTANDARD LVCMOS33 [get_ports hdmi_oen]
set_property PACKAGE_PIN R18 [get_ports hdmi_ddc_scl_io]
set_property IOSTANDARD LVCMOS33 [get_ports hdmi_ddc_scl_io]
set_property PACKAGE_PIN R16 [get_ports hdmi_ddc_sda_io]
set_property IOSTANDARD LVCMOS33 [get_ports hdmi_ddc_sda_io]

