set_property IOSTANDARD LVCMOS33 [get_ports {rtc_sclk}]
set_property PACKAGE_PIN R19 [get_ports {rtc_sclk}]
set_property IOSTANDARD LVCMOS33 [get_ports {rtc_ce}]
set_property PACKAGE_PIN L15 [get_ports {rtc_ce}]
set_property IOSTANDARD LVCMOS33 [get_ports {rtc_data}]
set_property PACKAGE_PIN L14 [get_ports {rtc_data}]