set_property BITSTREAM.GENERAL.COMPRESS TRUE [current_design]
set_property CONFIG_VOLTAGE 3.3 [current_design]
set_property CFGBVS VCCO [current_design]
set_property BITSTREAM.CONFIG.UNUSEDPIN PULLUP [current_design]

set_property PACKAGE_PIN Y9 [get_ports sys_clk]
set_property IOSTANDARD LVCMOS33 [get_ports sys_clk]

set_property PACKAGE_PIN J17 [get_ports {mdio_mdc          }]
set_property PACKAGE_PIN J16 [get_ports {mdio_mdio_io      }]
set_property PACKAGE_PIN L19 [get_ports {phy_rst_n         }]
set_property PACKAGE_PIN K19 [get_ports {rgmii_rxc         }]
set_property PACKAGE_PIN K20 [get_ports {rgmii_rx_ctl      }]
set_property PACKAGE_PIN J18 [get_ports {rgmii_rd[0]       }]
set_property PACKAGE_PIN K18 [get_ports {rgmii_rd[1]       }]
set_property PACKAGE_PIN J15 [get_ports {rgmii_rd[2]       }]
set_property PACKAGE_PIN K15 [get_ports {rgmii_rd[3]       }]
set_property PACKAGE_PIN R21 [get_ports {rgmii_txc         }]
set_property PACKAGE_PIN R20 [get_ports {rgmii_tx_ctl      }]
set_property PACKAGE_PIN N17 [get_ports {rgmii_td[0]       }]
set_property PACKAGE_PIN N18 [get_ports {rgmii_td[1]       }]
set_property PACKAGE_PIN N19 [get_ports {rgmii_td[2]       }]
set_property PACKAGE_PIN N20 [get_ports {rgmii_td[3]       }]


set_property IOSTANDARD LVCMOS33 [get_ports {mdio_mdc          }]
set_property IOSTANDARD LVCMOS33 [get_ports {mdio_mdio_io      }]
set_property IOSTANDARD LVCMOS33 [get_ports {phy_rst_n         }]
set_property IOSTANDARD LVCMOS33 [get_ports {rgmii_rxc         }]
set_property IOSTANDARD LVCMOS33 [get_ports {rgmii_rx_ctl      }]
set_property IOSTANDARD LVCMOS33 [get_ports {rgmii_rd[0]       }]
set_property IOSTANDARD LVCMOS33 [get_ports {rgmii_rd[1]       }]
set_property IOSTANDARD LVCMOS33 [get_ports {rgmii_rd[2]       }]
set_property IOSTANDARD LVCMOS33 [get_ports {rgmii_rd[3]       }]
set_property IOSTANDARD LVCMOS33 [get_ports {rgmii_txc         }]
set_property IOSTANDARD LVCMOS33 [get_ports {rgmii_tx_ctl      }]
set_property IOSTANDARD LVCMOS33 [get_ports {rgmii_td[0]       }]
set_property IOSTANDARD LVCMOS33 [get_ports {rgmii_td[1]       }]
set_property IOSTANDARD LVCMOS33 [get_ports {rgmii_td[2]       }]
set_property IOSTANDARD LVCMOS33 [get_ports {rgmii_td[3]       }]